#theme: jekyll-theme-minimal
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Discrete Technology: The Assistive Smart Jacket
description: Hello! My name is Anvika and I am a high school senior with a keen interest in computer engineering. This portfolio shares why I decided to develop discreet technology to assist the visually impaired, the technical details behind my project, and the invaluable lessons I’ve gained along the way!

